AWSTemplateFormatVersion: 2010-09-09
Resources:
  securitygroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: securitygroup
      GroupName: securitygroup
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: -1
          ToPort: -1

      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          Description: sg
          FromPort: -1
          IpProtocol: -1
          ToPort: -1

      VpcId: vpc-9ff4f8e7
      Tags: 
        - Key: Name
          Value: stack-sg